# Generated by Django 5.2.8 on 2025-11-09 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('homepage', models.URLField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='core.source')),
                ('topics', models.ManyToManyField(blank=True, related_name='articles', to='core.topic')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('model_name', models.CharField(default='baseline', max_length=255)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='core.article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_at'], name='core_articl_publish_a6a48c_idx'),
        ),
    ]
