# Generated by Django 5.2.8 on 2025-11-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='homepage',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
